---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap1
data:
  default.conf: |
    server {
      listen       80 default_server;
      server_name  _;
      default_type text/plain;
      location / {
        return 200 "\n'Hello World!'\n";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config
        configMap:
          name: my-configmap1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  namespace: api
spec:
  selector:
    app: app1
  ports:
  - port: 80
    targetPort: 80
    name: http


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap2
data:
  default.conf: |
    server {
      listen       80 default_server;
      server_name  _;
      default_type text/plain;
      location / {
        return 200 "\n'Hello Russia!'\n";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config2
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config2
        configMap:
          name: my-configmap2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  namespace: api
spec:
  selector:
    app: app2
  ports:
  - port: 80
    targetPort: 80
    name: http
